### ISSUE TITLE
[Bug]: Publish and unPublish events not working

### ISSUE THREAD

**Issue by wfpaisa** [ComfortablyCoding/strapi-plugin-io#15]
### What issue are you experiencing?

I get the  ["find", "findOne", "create", "update", "delete"] but no ["publish", "unpublish"]

  "dependencies": {
    "@strapi/plugin-documentation": "^4.1.7",
    "@strapi/plugin-graphql": "^4.1.7",
    "@strapi/plugin-i18n": "4.1.7",
    "@strapi/plugin-users-permissions": "4.1.7",
    "@strapi/provider-email-nodemailer": "^4.1.8",
    "@strapi/strapi": "4.1.7",
    "better-sqlite3": "7.4.6",
    "strapi-plugin-io": "^1.1.0"
  },

![image](https://user-images.githubusercontent.com/1735752/163736873-fbf5790b-31e5-4dde-85a0-ed1a5624d058.png)
![image](https://user-images.githubusercontent.com/1735752/163736897-87a023eb-bf77-4007-9858-70bbb9182c92.png)

### Steps To Reproduce

1. Basic create a content
2. WS From Strapi editor click in button publish, and unPublish
3. Response no get data

### What version of the plugin are you using?

  "strapi-plugin-io": "^1.1.0"

### What strapi version are you using?

@strapi/strapi": "4.1.7",

**Comment by FabioFuschi-SNK** [comment]
I have a similar problem with the "SINGLE TYPES" where the action name is "createOrUpdate", and the role permission has just "update" as an action, so events are not emitted on saving a single types.

**Comment by ComfortablyCoding** [comment]
The (un)publish not being accounted for will be fixed in the next release.

**Comment by FabioFuschi-SNK** [comment]
Hello @ComfortablyCoding, thank you for that fix. Unfortunately the publish event for "SINGLE TYPES" still not work, i think the reason is that you change the event name from "publish" to "create", but that types don't have a permission for "create", because it is already created. So for this types it must  be "update" instead of "create".

**Comment by ComfortablyCoding** [comment]
I haven't published a new release yet. But you are correct, I will merge a fix before releasing the new version. Why they have different events for single types is beyond me.

**Comment by ComfortablyCoding** [comment]
Released in v1.1.1
