### ISSUE TITLE
[Bug]: Can't receive Update events

### ISSUE THREAD

**Issue by macojaune** [ComfortablyCoding/strapi-plugin-io#24]
### What issue are you experiencing?

I'm using socket.io-client on a Nextjs front and it's connecting correctly, when I use .onAll() 
I have all the events  like find, findOne but not the create or update.

I use plugin configuration with "contentTypes: '*'" for my tests 

### What version of the plugin are you using?

1.1.1

### What strapi version are you using?

4.1.10

**Comment by macojaune** [comment]
Okay nevermind, I didn't think Permissions would play a role in these events.

With the permissions allowed to My Public role on the update,create. It works correctly.

**Comment by macojaune** [comment]
Okay nevermind, I didn't think Permissions would play a role in these events.

With the permissions allowed to My Public role on the update,create. It works correctly.

**Comment by hrdunn** [comment]
Glad you figured it out, you can also use the following in your controllers to circumvent the Permissions checking.
```
strapi.$io.raw("customEvent", data);
```
