### ISSUE TITLE
[FR]: Add API Tokens support

### ISSUE THREAD

**Issue by tomstorms** [ComfortablyCoding/strapi-plugin-io#37]
### What issue are you experiencing?

Looking for a working example using the 'API Tokens' (https://docs.strapi.io/user-docs/latest/settings/managing-global-settings.html#managing-api-tokens) rather than user JWT tokens (or whether anyone has a workaround?).

When I dig further, can see it fails in the jsonwebtoken module (verify.js, line 63) flagging that the token provided is "jwt malformed" and missing the 3 dot (.) parts of the JWT token.

### What version of the plugin are you using?

1.1.2

### What strapi version are you using?

4.5.1

**Comment by ComfortablyCoding** [comment]
Thanks for the report I will need to look into this. At the moment no, it will not work with API tokens.

**Comment by ComfortablyCoding** [comment]
This should be available in v2, feel free to check it out early using the v2.0.0 branch. 

NOTE: As its a major version their are breaking changes.

**Comment by maxval1** [comment]
Something news when it would be released ?

**Comment by ComfortablyCoding** [comment]
I have not gotten much feedback on the newer version.

I will do some final testing and try and get at least an alpha of it released soon. Since their was not much feedback hopefully everything is resolved and works as expected in the newer version.

**Comment by ComfortablyCoding** [comment]
This is now possible in the lastest v2 release.
