### ISSUE TITLE
[Bug]: Error on create or edit collection-type

### ISSUE THREAD

**Issue by mdwillian** [ComfortablyCoding/strapi-plugin-io#38]
### What issue are you experiencing?

When creating or editing content of a content-type in the content-manager of a collection-type that has a property of type component and has a relationship with another collection-type, the following error occurs "Cannot read properties of undefined (reading 'split ')" in the getModelMeta method.

### Steps To Reproduce

1. Install the strapi-plugin-io plugin in a new strapi project
2. Run the project with the develop script and access the strapi admin
3. Access the content-type builder menu
4. Create a new component that has a property that is of type relation with a collection-type. Eg: Comment that has relationship with User.
5. Create a collection type that has a property of the new component's type. Eg: Post that has comments
6. Access the content-manager menu
7. Access the collection-type that has the property of the type of the component Ex.: Post
8. When creating a new entry in the field of type component when adding a new entry and adding the relation there will be no relation available and will have the error in the console: Cannot read properties of undefined (reading 'split')

### What version of the plugin are you using?

1.1.2

### What strapi version are you using?

4.5.1

**Comment by ComfortablyCoding** [comment]
Thanks for the report, this should be fixed by #43
