### ISSUE TITLE
[Bug]: getModelMeta fails with Strapi 4.5.5

### ISSUE THREAD

**Issue by Brianggalvez** [ComfortablyCoding/strapi-plugin-io#42]
### What issue are you experiencing?

Withe the new UI for better relation handling, the following error appears in console:

` Cannot read properties of undefined (reading 'split')
    at getModelMeta`
this is caused because now they are attaching the action to the model, for instance: 
`{ model: 'report.reports.findExisting' }`

### What version of the plugin are you using?

1.1.4

### What strapi version are you using?

4.5.5

**Comment by ComfortablyCoding** [comment]
This should be fixed by #43
