### ISSUE TITLE
createOrUpdate does not work

### ISSUE THREAD

**Issue by ChristopheCVB** [ComfortablyCoding/strapi-plugin-io#51]
https://github.com/ComfortablyCoding/strapi-plugin-io/blob/25b9141d2bbe1d447e9e3efec12cc5a955823489/server/middlewares/io.js#L8

```json
{
  "contentTypes": {
    "home": { "createOrUpdate": true },
    "quiz": { "createOrUpdate": true },
    "team": { "update": true }
  },
  "model": "api::quiz.quiz.update"
}
```

Content Types from the plugin config with `createOrUpdate` does not get validated by 
https://github.com/ComfortablyCoding/strapi-plugin-io/blob/25b9141d2bbe1d447e9e3efec12cc5a955823489/server/utils/isValidContentTypeRoute.js#L26

**Comment by ComfortablyCoding** [comment]
Possible they changed something in the last few versions. I will look into this.

**Comment by ComfortablyCoding** [comment]
The config you have for your content types is incorrect, it should be a String or String[] value per the [documentation](https://github.com/ComfortablyCoding/strapi-plugin-io#the-complete-plugin-configuration-object), you can see a [sample configuration](https://github.com/ComfortablyCoding/strapi-plugin-io#sample-configuration) for further reference.

If you change your config to 
```js
 "contentTypes": {
    "home": "createOrUpdate",
    "quiz": "createOrUpdate",
    "team": "update"
  },
```
it will work

**Comment by ChristopheCVB** [comment]
So sorry about that :/
