### ISSUE TITLE
[Bug]: After installing the package strapi gives an error

### ISSUE THREAD

**Issue by Sazzad-Anwar** [ComfortablyCoding/strapi-plugin-io#85]
### What issue are you experiencing?

![Screenshot_2](https://github.com/ComfortablyCoding/strapi-plugin-io/assets/39345523/500a9f32-0d2d-4cfe-8842-fa0f9d5f370d)

I have installed the strapi and installed strapi-plugin-io. Then I have added the plugin.ts file inside config folder and added the code as in documentation. Then I build the project. After that while starting strapi throws me the error.

Strapi Version: 4.17.1
NPM Version: 9.8.1
Node Version: 18.18.0

### What version of the plugin are you using?

2.0.5

### What strapi version are you using?

4.17.1

**Comment by ComfortablyCoding** [comment]
The file name should be `plugins.ts`, not `plugin.ts`.
